spring.application.name=subscription_billing_b2b

##-Postgres properties-##
spring.datasource.url=jdbc:postgresql://postgres-db:5432/billing_db
spring.datasource.username=root
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
##----------------------##

##-Liquibase properties-##
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.yaml
##-----------------------##

##----JWT properties-----##
application.security.jwt.secret-key=kQLWkcQ12dmnd5w21kAMcwrEu12e901C
application.security.jwt.jwt-expiration-minute=15
##-----------------------##

##-----Refresh token-----##
application.security.refresh-token.refresh-token-expiration-day=15

##-----Email Sender-----##
application.email.corporate-email-adress=kovaletsandrii@gmail.com
application.email.api-key=kqqkd
application.frontend.url=${FRONTEND_URL:http://localhost:3000}
